const SHOW_LOADING = 'SHOW_LOADING'
const TOGGLE_COMPLETE = 'TOGGLE_COMPLETE'
const CHANGE_TYPE = 'CHANGE_TYPE'
const LOGIN = 'LOGIN'
const LOGOUT = 'LOGOUT'
const SHOW_ERROR = 'SHOW_ERROR'
const SET_PRODUCTS = 'SET_PRODUCTS'

export {
    SHOW_LOADING,
    TOGGLE_COMPLETE,
    CHANGE_TYPE,
    LOGIN,
    LOGOUT,
    SHOW_ERROR,
    SET_PRODUCTS,
}
